#!/usr/bin/env python

'''Convert a C3D file to NPZ (numpy binary) format.'''

from __future__ import print_function

import c3d
import argparse
import gzip
import numpy as np
import sys
from tempfile import TemporaryFile

parser = argparse.ArgumentParser(description='Convert a C3D file to NPZ (numpy binary) format.')
parser.add_argument('input', default='-', metavar='FILE', nargs='+', help='process data from this input FILE')

def convert(filename, args):
    input = sys.stdin
    outname = '-'
    output = TemporaryFile()
    if filename != '-':
        input = open(filename, 'rb')
        outname = filename.replace('.c3d', '.npz')
        
    points = []
    analog = []
    for i, (_, p, a) in enumerate(c3d.Reader(input).read_frames()):
        points.append(p)
        analog.append(a)
        if i and not i % 10000:
            logging.info('%s: extracted %d point frames',
                         outname, len(points))
    
    np.savez(output, points=points, analog=analog)
    print(outname + ': saved', len(points), "x", str(points[0].shape), "points,", 
        len(analog), analog[0].shape, 'analog' if len(analog) else ()
    )
    
    if filename != '-':
        input.close()
        output.close()


def main(args):
    for filename in args.input:
        convert(filename, args)


if __name__ == '__main__':
    main(parser.parse_args())
